# Generated by Django 3.0.4 on 2020-04-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=400)),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
